
project:
  type: website

website:
  title: "Wouter Ryckbosch"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Posts"
        href: posts/index.qmd
  page-footer: "© 2025 Wouter Ryckbosch"

format:
  html:
    theme: cosmo
    toc: true
